apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: AI Platform GitOps project

  sourceRepos:
    - https://github.com/anselem-okeke/ai-platform-gitops.git
    - ghcr.io/sigstore/helm-charts
    - ghcr.io/github/artifact-attestations-helm-charts

  destinations:
    - namespace: ai-platform
      server: https://kubernetes.default.svc

    - namespace: ai-platform-operator-system
      server: https://kubernetes.default.svc

    - namespace: monitoring
      server: https://kubernetes.default.svc

    - namespace: gateway-system
      server: https://kubernetes.default.svc

    - namespace: argocd
      server: https://kubernetes.default.svc

    - namespace: cosign-system
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

    - group: rbac.authorization.k8s.io
      kind: ClusterRole

    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

    - group: gateway.networking.k8s.io
      kind: GatewayClass

    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicy

    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicyBinding

    - group: policy.sigstore.dev
      kind: TrustRoot

    - group: policy.sigstore.dev
      kind: ClusterImagePolicy

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: "apps"
      kind: Deployment
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "apps"
      kind: StatefulSet
    - group: "policy"
      kind: PodDisruptionBudget
    - group: "networking.k8s.io"
      kind: NetworkPolicy
    - group: "gateway.networking.k8s.io"
      kind: Gateway
    - group: "gateway.networking.k8s.io"
      kind: HTTPRoute
    - group: "monitoring.coreos.com"
      kind: ServiceMonitor
    - group: "monitoring.coreos.com"
      kind: PrometheusRule
    - group: "platform.anselem.dev"
      kind: ModelService
    - group: "argoproj.io"
      kind: Application
    - group: "gateway.envoyproxy.io"
      kind: SecurityPolicy

