apiVersion: v1
kind: ConfigMap
metadata:
  name: kserve-model-reader-policy
  namespace: model-storage
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: kserve-model-reader
    app.kubernetes.io/part-of: ai-platform
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:GetBucketLocation",
            "s3:ListBucket"
          ],
          "Resource": [
            "arn:aws:s3:::models"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "s3:GetObject"
          ],
          "Resource": [
            "arn:aws:s3:::models/*"
          ]
        }
      ]
    }
