apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kserve-model-reader-credentials
  namespace: model-storage
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: kserve-model-reader
    app.kubernetes.io/part-of: ai-platform
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: kserve-model-reader-credentials
    creationPolicy: Owner

  data:
    - secretKey: access-key
      remoteRef:
        key: ai-platform/model-storage/kserve-reader
        property: access-key

    - secretKey: secret-key
      remoteRef:
        key: ai-platform/model-storage/kserve-reader
        property: secret-key
