apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secret.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - bucket-bootstrap-job.yaml
  - kserve-reader-external-secret.yaml
  - kserve-reader-policy-configmap.yaml
  - kserve-reader-bootstrap-job.yaml
