apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: model-storage
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: model-storage
    app.kubernetes.io/part-of: ai-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
