apiVersion: v1
kind: Secret
metadata:
  name: minio-root-credentials
  namespace: model-storage
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: ai-platform
type: Opaque
