apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ai-platform-api
    newName: ghcr.io/anselem-okeke/ai-platform-api
    digest: sha256:02e0c2c9a1cbbc34f92d1aceb94c7b9b0c9d620eced4b78deb2099a23a29bc74
