apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ai-platform-api
    newName: ghcr.io/anselem-okeke/ai-platform-api
    digest: sha256:5d3ac13e699004f1e96dd703ff256d15ddfce1fe3a66cfd852d9b0eba8579a09
