apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ai-platform-api
    newName: ghcr.io/anselem-okeke/ai-platform-api
    digest: sha256:d4cf8c7d63fd981c5398d7e210932bb15f9d3bf0d21ac007ce85dac95ebe9436
