apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - image-admission-policy.yaml
  - image-admission-policy-binding.yaml
  - pod-image-admission-policy.yaml
  - pod-image-admission-policy-binding.yaml
