apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: vault-store
    app.kubernetes.io/part-of: ai-platform
spec:
  provider:
    vault:
      server: https://vault.platform.local:8200
      path: secret
      version: v2

      caProvider:
        type: ConfigMap
        name: vault-ca
        namespace: external-secrets
        key: ca.crt

      auth:
        kubernetes:
          mountPath: kubernetes-kind
          role: external-secrets

          serviceAccountRef:
            name: external-secrets-vault
            namespace: external-secrets
            audiences:
              - vault
