apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ai-platform-operator
    newName: ghcr.io/anselem-okeke/ai-platform-operator
    digest: sha256:621bebe7e5dcf34bc55768777bfbde043a1abf8cc53e4fc8ec3dce4f914c2d41
