apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ai-platform-operator
    newName: ghcr.io/anselem-okeke/ai-platform-operator
    digest: sha256:6600bcc5dc644bc112b235a3c6a554a73211a4f1bf6aed720825016e4f0bcdc2
