apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ai-platform-operator
    newName: ghcr.io/anselem-okeke/ai-platform-operator
    digest: sha256:e8e0c4b2db8aeaa1d7f53cc42c5ecf477e0e64f94714bb82dec0f99ece4dedf8
