apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-api
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ai-platform

  source:
    repoURL: https://github.com/anselem-okeke/ai-platform-gitops.git
    targetRevision: HEAD
    path: platform/api/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform

  syncPolicy:
    syncOptions:
      - CreateNamespace=false
