apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kserve-crd.yaml
  - kserve.yaml
  - operator.yaml
  - api.yaml
  - gateway.yaml
  - monitoring.yaml
  - modelservices.yaml
  - policies.yaml
  - policy-controller.yaml
  - trust-policies.yaml
  - namespaces.yaml
