apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-storage
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: ai-platform

  source:
    repoURL: https://github.com/anselem-okeke/ai-platform-gitops.git
    targetRevision: HEAD
    path: platform/model-storage/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: model-storage

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: minio-root-credentials
      namespace: model-storage
      jsonPointers:
        - /data

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
