apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-namespaces
  namespace: argocd
spec:
  project: ai-platform

  source:
    repoURL: https://github.com/anselem-okeke/ai-platform-gitops.git
    targetRevision: main
    path: platform/namespaces/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
