apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-controller
  namespace: argocd
spec:
  project: ai-platform

  source:
    repoURL: ghcr.io/sigstore/helm-charts
    chart: policy-controller
    targetRevision: 0.10.6
    helm:
      releaseName: policy-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
