apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-model-reader
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: kserve-model-reader
    app.kubernetes.io/component: model-storage-access
    app.kubernetes.io/part-of: ai-platform

automountServiceAccountToken: false

secrets:
  - name: kserve-model-reader
