apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - writer-external-secret.yaml
  - iris-upload-job.yaml
  - breast-cancer-upload-job.yaml
configMapGenerator:
  - name: model-artifact-uploader
    files:
      - upload-model.py
