apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - writer-external-secret.yaml
  - iris-upload-job.yaml
configMapGenerator:
  - name: iris-artifact-uploader
    files:
      - upload-iris.py
